#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh
#cp 0/alpha.solid.orig 0/alpha.solid
runApplication topoSet -dict system/topoSetDict1
runApplication refineMesh -overwrite -dict system/refineMeshDict1
#rm log.topoSet
#rm log.refineMesh
#runApplication topoSet -dict system/topoSetDict2
#runApplication refineMesh -overwrite -dict system/refineMeshDict2
#runApplication setFields 
runApplication decomposePar
runParallel `getApplication`




#------------------------------------------------------------------------------
